export const PARTNERS = [
  { img: './assets/image/partner-1.png' },
  { img: './assets/image/partner-2.png' },
  { img: './assets/image/partner-3.png' },
  { img: './assets/image/partner-4.png' },
  { img: './assets/image/partner-5.png' },
  { img: './assets/image/partner-6.png' },
  { img: './assets/image/partner-7.png' },
  { img: './assets/image/partner-8.png' },
  { img: './assets/image/partner-9.png' },
  { img: './assets/image/partner-10.png' },
  { img: './assets/image/partner-11.png' },
  { img: './assets/image/partner-12.png' },
  { img: './assets/image/partner-13.png' },
  { img: './assets/image/partner-14.png' },
  { img: './assets/image/partner-15.png' },
  { img: './assets/image/partner-16.png' },
  { img: './assets/image/partner-17.png' },
  { img: './assets/image/partner-18.png' },
  { img: './assets/image/partner-19.png' },
  { img: './assets/image/partner-20.png' },
  { img: './assets/image/partner-21.png' },
  { img: './assets/image/partner-22.png' },
];
